<program> ::= { <statement> | <function> }

<statement> ::= <instruction> | <if> | <switch> | <while>

<instruction> ::= <identifier> { <value> } <newline>

<identifier> ::= <letter> { <letter> | <digit> }

<value> ::= <literal> | <variable>

<literal> ::= <number> | <string> | <bool>

<number> ::= [ '+' | '-' ] <float> | <int>

<float> ::= <digit> { <digit> } [ '.' <digit> { <digit> } ]

<int> ::= <digit> { <digit> }

<string> ::= '"' { <character> } '"'

<bool> ::= "true" | "false"

<variable> ::= "$" <identifier>

<if> ::= "if" <value> ':' { <statement> } [ <else> ] ';'

<switch> ::= "switch" <value> ':' { <case> } [ <else> ] ';'

<case> ::= "case" <value> ':' { <statement> } ';'

<else> ::= "else" ':' { <statement> }

<while> ::= "while" <value> ':' { <statement> } ';'

<function> ::= "func" <identifier> '(' [ <variable-list> ] ')' '>' '(' [ <variable-list> ] ')' ':' { <statement> } ';'

<variable-list> ::= <variable> { ',' <variable> }
